### ISSUE TITLE
Event materials (name badges) printed and ready

### ISSUE THREAD

**Issue by BatoolMM** [aim-rsf/ecr-day#25]
# Badges
- [x] Locate badge templates
- [x] Include names, logos, and RCs for all participants
- [x] Trim and encase them in plastic
- [x] Store them at the Turing
- [x] Get stickers to put on badges showing if people consent to their pictures being taken

# Booklets
- [x] Create plain English summaries from COMPUTE
- [x] Purchase the necessary papers
- [x] Arrange for printing at Liverpool University
- [x] Take them to a stationery shop to trim margins and bind them into booklets
- [x] RSF want to share AIM booklet, which contain plain language summaries of each RCs win Zenodo to make it citable under the name of the RCs as author. Any RCs who aren’t comfortable with this approach, can you inform Baool by

**Comment by eirini-zormpa** [comment]
I spoke to @evelinag about the picture consent and her suggestion was to ask people when they come to pick up their badges whether they are okay with their picture being taken and put the relevant sticker on

**Comment by AlexandraAAJ** [comment]
Hi Batool, here are some badges templates.
- Official Turing Institute: https://thealanturininstitute.sharepoint.com/:w:/s/ee/EVHIZLs0xeVJvnLcqm_dLoUBr1ZimlM4JYCWSMzDhpaaOw?e=nfSPib
- Template for TTW events: https://docs.google.com/document/d/1DCAEg1oskQZazP824zoqVSf-tqa2GANq/edit
Are you using only one room? If you're other rooms we added a little emoji at the bottom left to indicate which room people were directed to. I can send you that template too, if necessary.

**Comment by eirini-zormpa** [comment]
[heart]         Eirini Zormpa reacted to your message:
________________________________

**Comment by BatoolMM** [comment]
@eirini-zormpa thank you for discussing it with @evelinag - I love the idea but my only concern is that if we do that with verbal confirmation during the day, I would not have any record that I can share with comms/data protection when I use these photos in the website or any of our comms. Sorry, is there any other way we can around it while also keeping a record of it?

**Comment by eirini-zormpa** [comment]
hmmm good point! would it work if I printed out a sheet with their names and they had to sign next to their name?

**Comment by BatoolMM** [comment]
That sounds very good, would you be able to check the phrasing of what is needed to be signed on in the sheet with Dr Kit Good from the Data Protection Manager, he is very nice and flexible (mailto:kgood@turing.ac.uk), Just to make sure what they are signing is what actually needed from data protection team.

**Comment by eirini-zormpa** [comment]
Will do!

**Comment by BatoolMM** [comment]
This the new badges templates: https://docs.google.com/document/d/1j6Q6V8Er3O6LoHxcxUG9t1zqKil6B6uGCIVxSpzcKoA/edit?usp=sharing

Not yet printed

**Comment by BatoolMM** [comment]
Copying this email from Kit Good from data protection who @Eirini has emailed him to ask about the photography on 9th of Nov:

>1) Group photos
 
>If you are taking group photos such as 'Attendees at our conference' then the following should be in place:
 
>Recording or filming
 
>If you are intending to record meetings, take photos or film sessions you should explain this to potential attendees in advance.
 
>In advance of the event and at the start of virtual or in person session you should inform individuals that the event will be recorded. For virtual sessions this will give attendees the option to mute or turn off their camera before recording starts.
 
>Photography
 
>If you are taking photos of the event, notify attendees in advance. On the day of the event, have clear signage in place, including contact details where an individual can raise any concerns with a Turing representative. Consider having clear ‘non-photo’ areas where individuals can stand if they do not wish to be photographed. Your badges idea is also acceptable.
 
>After the event
 
>If you are adding content from the event to the Turing website or one of the Turing social media channels, you need to ensure that this has been stated to participants beforehand.
 
>2) Portrait photos
 
>If you are taking portrait style photos, such as 'Kit Good attending our event', then a photo consent form, which explains what the photo will be used for and how long it will be kept for, should be signed by the individual and kept by the team. I would consult the events team to see what form they use, to ensure consistency.

**Comment by BatoolMM** [comment]
Thank you again @eirini-zormpa ❤️
